name: MLflow CI - Prediksi Balita Stunting

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Setup Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.7"

    # 3. Install dependencies
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r MLProject/requirements.txt
        pip install mlflow scikit-learn pandas

    # 4. Run training script (modelling.py)
    - name: Run training script
      working-directory: MLProject
      run: python modelling.py

    # 5. Upload MLflow artifacts (opsional, untuk backup)
    - name: Upload MLflow artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: model-artifact-mlruns
        path: MLProject/mlruns/

    # 6. Get latest MLflow run_id
    - name: Get latest MLflow run_id
      id: get_run_id
      run: |
        RUN_ID=$(cat MLProject/run_id.txt)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "Found Run ID: $RUN_ID"

    # 7. Login to Docker Hub
    - name: Login to Docker Hub
      if: success()
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 8. Build Docker image using MLflow
    - name: Build Docker Image with MLflow
      working-directory: MLProject
      env:
        MLFLOW_TRACKING_URI: file:./MLProject/mlruns
      run: |
        echo "Building Docker image for Run ID: ${{ env.RUN_ID }}"
        mlflow models build-docker \
          --model-uri "runs:/${{ env.RUN_ID }}/model" \
          --name "predictive-maintenance-local" \
          --enable-mlserver

    # 9. Tag Docker image
    - name: Tag Docker Image
      run: |
        docker tag predictive-maintenance-local ${{ secrets.DOCKER_USERNAME }}/predictive-maintenance:latest

    # 10. Push Docker image
    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/predictive-maintenance:latest
