import mlflow
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

def run_model():
    print("Memulai training model...")

    # Load dataset
    dataset_path = "MLProject/stunting_balita_preprocessing.csv"
    print(f"Mencari dataset di: {dataset_path}")
    data = pd.read_csv(dataset_path)
    print("Dataset berhasil diload")

    X = data.drop("target", axis=1)
    y = data["target"]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Mulai MLflow run baru
    with mlflow.start_run():  # <--- pastikan TIDAK ada run_id
        model = RandomForestClassifier(n_estimators=100, random_state=42)
        model.fit(X_train, y_train)

        preds = model.predict(X_test)
        acc = accuracy_score(y_test, preds)
        print(f"Accuracy: {acc}")

        mlflow.log_metric("accuracy", acc)
        mlflow.sklearn.log_model(model, "random_forest_model")

if __name__ == "__main__":
    run_model()
